In [1]:
import pandas as pd
import os

In [2]:
csv_file = os.path.join('Global_Mobility_Report.csv')

In [3]:
mob_df = pd.read_csv(csv_file)

/Users/tyler/opt/anaconda3/envs/ProjectWork/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3062: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
mob_df

,country_region_code,country_region,sub_region_1,sub_region_2,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,NaN,NaN,NaN,NaN,2020-02-15,0.0,4.0,5.0,0.0,2.0,1.0
1,AE,United Arab Emirates,NaN,NaN,NaN,NaN,2020-02-16,1.0,4.0,4.0,1.0,2.0,1.0
2,AE,United Arab Emirates,NaN,NaN,NaN,NaN,2020-02-17,-1.0,1.0,5.0,1.0,2.0,1.0
3,AE,United Arab Emirates,NaN,NaN,NaN,NaN,2020-02-18,-2.0,1.0,5.0,0.0,2.0,1.0
4,AE,United Arab Emirates,NaN,NaN,NaN,NaN,2020-02-19,-2.0,0.0,4.0,-1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547917,ZW,Zimbabwe,Midlands Province,NaN,ZW-MI,NaN,2020-06-10,NaN,NaN,NaN,NaN,-5.0,NaN
547918,ZW,Zimbabwe,Midlands Province,NaN,ZW-MI,NaN,2020-06-11,NaN,NaN,NaN,NaN,-4.0,NaN
547919,ZW,Zimbabwe,Midlands Province,NaN,ZW-MI,NaN,2020-06-12,NaN,NaN,NaN,NaN,-4.0,NaN
547920,ZW,Zimbabwe,Midlands Province,NaN,ZW-MI,NaN,2020-06-13,NaN,NaN,NaN,NaN,24.0,NaN
547921,ZW,Zimbabwe,Midlands Province,NaN,ZW-MI,NaN,2020-06-14,NaN,NaN,NaN,NaN,18.0,NaN